= Data file struct
:doctype: book

The EDI Gateway produces an ASCII data file for outbound transactions.
For inbound transactions, EDI Gateway processes an ASCII data file produced by the EDI translator software that contains the trading partner's business data.
Each data file consists of several records.
Each record has two sections, the record key (positions 1-100) and the application data area (positions 101 to 600).

The structure is shown in the following table

Data	Position	Length Common Key (1-100) Trading Partner Code (short)	1-25	25 Key 1 (primary document identifier)	26-47	22 Key 2	48-69	22 Key 3	70-91	22 Record Number	92-95	4 Record Number	96-97	2 Record Qualifier	98-100	3 Application Data (101 - 512+)	101-600	500

= Sample of 277 EDI Message

19=AN,2,30,City Name 26=ID,2,3,Country Code 28=NO,1,9,Group Control Number 66=ID,1,2,Identification Code Qualifier 67=AN,2,80,Identification Code 93=AN,1,60,Name 96=NO,1,9,Number of Included Segments 97=NO,1,6,Number of Transaction Sets Included 98=ID,2,3,Entity Identifier Code 101=ID,2,2,Authorization Information Qualifier 102=AN,10,10,Authorization Information 103=ID,2,2,Security Information Qualifier 104=AN,10,10,Security Information 105=ID,2,2,Interchange ID Qualifier 106=AN,15,15,Interchange Sender ID 107=AN,15,15,Interchange Receiver ID 108=AN,6,6,Interchange Date 109=TM,4,4,Interchange Time 111=ID,5,5,Interchange Control Version Number 112=NO,9,9,Interchange Control Number 113=ID,1,1,Acknowledgment Requested 114=ID,1,1,Interchange Usage Indicator 115=ID,1,1,Component Element Separator 116=ID,3,15,Postal Code 124=AN,2,15,Application Receiver Code 127=AN,1,80,Reference Identification 128=ID,2,3,Reference Identification Qualifier 142=AN,2,15,Application Sender Code 143=ID,3,3,Transaction Set Identifier Code 156=ID,2,2,State or Province Code 165=ID,1,1,Repetition Separator 166=AN,1,55,Address Information 234=AN,1,80,Product Service ID 235=ID,2,2,Product Service ID Qualifier 306=ID,1,2,Action Code 309=ID,1,2,Location Qualifier 310=AN,1,30,Location Qualifier 329=AN,4,9,Transaction Set Control Number 337=TM,4,8,Time 352=AN,1,80,Description 353=ID,2,2,Transaction Set Purpose Code 364=AN,1,256,Communication Number 365=ID,2,2,Communication Number Qualifier 366=ID,2,2,Contact Function Code 373=DT,8,8,Date 374=ID,3,3,Date Time Qualifier 380=R,1,15,Quantity 429=AN,1,16,Check Number 443=AN,1,20,Contact Inquiry Reference 455=ID,1,2,Responsible Agency Code 479=ID,2,2,Functional Identifier Code 480=AN,1,12,Version Release Industry Identifier Code 481=ID,1,2,Trace Type Code 509=AN,10,10,Originating Company Identifier 591=ID,3,3,Payment Method Code 628=AN,1,12,Hierarchical ID Number 640=ID,2,2,Transaction Type Code 706=ID,2,2,Entity Relationship Code 734=AN,1,12,Hierarchical Parent ID Number 735=ID,1,2,Hierarchical Level Code 736=ID,1,1,Hierarchical Child Code 755=ID,2,2,Report Type Code 782=R,1,18,Monetary Amount 933=AN,1,264,Free form Message Text 1005=ID,4,4,Hierarchical Structure Code 1035=AN,1,60,Name Last or Organization Name 1036=AN,1,35,Name First 1037=AN,1,25,Name Middle 1038=AN,1,10,Name Prefix 1039=AN,1,10,Name Suffix 1065=ID,1,1,Entity Type Qualifier 1250=ID,2,3,Date Time Period Format Qualifier 1251=AN,1,35,Date Time Period 1270=ID,1,3,Code List Qualifier Code 1271=AN,1,30,Industry Code 1339=AN,2,2,Procedure Modifier 1369=AN,1,2,Tooth Surface Code 1705=AN,1,35,Implementation Convention Reference 1715=ID,1,3,Country Subdivision Code 11111112=NO,1,9,Interchange Control Number 11111116=NO,1,5,Number of Included Functional Groups
